name: Build GitBook

on:
  push:
    branches:
      - main  # 触发条件：当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新版本的 Ubuntu

    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10.24.1  # 指定 Node.js 版本

      - name: Debug Info
        run: |
          ls -al && pwd   # 列出当前目录下的文件

      - name: Build GitBook
        run: |
          cd /home/runner/work/PromptSkillBuilders/
          ls -al && pwd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用部署到 GitHub Pages 的 Action
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/PromptSkillBuilders/_book  # 需要发布的目录，这里是 GitBook 构建输出目录


